version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src/MockClassifier.Api/"
    schedule:
      interval: "daily"
      time: "22:00"

  - package-ecosystem: "nuget"
    directory: "/src/MockClassifier.IntegrationTests/"
    schedule:
      interval: "daily"
      time: "23:00"
 
  - package-ecosystem: "nuget"
    directory: "/src/MockClassifier.UnitTests/"
    schedule:
      interval: "daily"
      time: "18:00"
      
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "daily"
      time: "19:00"