namespace MockClassifier.Api.Services.Dmr
{
    /// <summary>
    /// The key headers used to interact with Dmr
    /// </summary>
    public class DmrRequestHeaders
    {
        /// <summary>
        /// Name of the participant that sent the message.
        /// </summary>
        public string SentBy { get; set; }

        /// <summary>
        /// Uuid generated by the sender of a message for correlating async responses to a specific request.
        /// </summary>
        public string MessageId { get; set; }

        /// <summary>
        /// Participant name to send the message to.
        /// </summary>
        public string SendTo { get; set; }

        /// <summary>
        /// Reference to the original X-Message-Id we are replying to.
        /// </summary>
        public string MessageIdRef { get; set; }
    }
}
