name: Mock Classifier CI Pipeline

# push is only for developing th pipline itself. When complete it shoudl only be on PRs to [main]
on:
  push:
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: src

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Dotnet Restore Tools
      run: dotnet tool restore
        
    - name: Dotnet Restore
      run: dotnet restore 
        
    - name: Dotnet Format
      run: dotnet format --no-restore
      
    - name: Dotnet Build
      run: dotnet build --no-restore
     
  UnitTest:
    runs-on: ubuntu-latest

    steps:
    - name: Dotnet Test (unit tests only)
      run: dotnet test *.UnitTests/*.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
      
    - name: Copy Coverage output to root
      run: cp *.UnitTests/TestResults/**/coverage.cobertura.xml coverage.cobertura.xml
      
# Have set threshold to 20% for developing the pipeline itself. Should be 80% when completed.
    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: /../coverage.cobertura.xml
        fail_below_min: true
        format: markdown
        output: both
        thresholds: '20'
        
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2.2.0
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
  
  MutationTest:
    runs-on: ubuntu-latest

    steps:
    - name: Mutation Test
      run: dotnet stryker
    
    - name: Upload Mutation Report
      uses: actions/upload-artifact@v3.0.0
      with:
        name: mutation-report
        path: StrykerOutput
