name: Mock Classifier CI Pipeline

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Dotnet Restore
      run: dotnet restore src/*.sln 
        
    - name: Dotnet Format
      run: dotnet format src/*.sln --no-restore
      
    - name: Dotnet Build
      run: dotnet build src/*.sln --no-restore
      
    - name: Dotnet Test
      run: dotnet test src/*.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"
